### import Dependencies

In [1]:
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PayloadSchemaType, PointStruct, MatchAny, FieldCondition, Filter, Prefetch, FusionQuery

import pandas as pd
import numpy as np
import openai
import json
import tiktoken

/Users/antoineestienne/GithubRepositories/ai-bootcamp-dev-repo/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Retrieve all item IDs from Amazon Items Qdrant Collection

In [2]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [3]:
dummy_vector = np.zeros(1536).tolist()

In [5]:
payload = qdrant_client.query_points(
    collection_name="Amazon-items-collection-01-hybrid-search",
    query=dummy_vector,
    using="text-embedding-3-small",
    limit=1000,
    with_payload=["parent_asin"],
    with_vectors=False
)

In [6]:
payload.points

[ScoredPoint(id=492, version=2, score=0.0, payload={'parent_asin': 'B0BFGXRMJN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=385, version=2, score=0.0, payload={'parent_asin': 'B09SYSRBLC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=386, version=2, score=0.0, payload={'parent_asin': 'B09Z2NG36C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=389, version=2, score=0.0, payload={'parent_asin': 'B09XCJZKSR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=330, version=2, score=0.0, payload={'parent_asin': 'B09ZPMPNVH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=148, version=2, score=0.0, payload={'parent_asin': 'B0CGHVQ4M3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=293, version=2, score=0.0, payload={'parent_asin': 'B0C3X7JK7R'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=375, version=2, score=0.0, payload={'parent_asin': 'B09VDNKL4G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=387, version=2, score=0.0, payload={'parent_asin': 'B0BGJ2TDXV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=456, version=2, score=0.0, payload={'parent_asin': 'B0BHSPB4JL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=66, version=2, score=0.0, payload={'parent_asin': 'B0BP68QCZ2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=223, version=2, score=0.0, payload={'parent_asin': 'B09TR8VXGL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=39, version=2, score=0.0, payload={'parent_asin': 'B0CGM29ZL7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=12, version=2, score=0.0, payload={'parent_asin': 'B0C9XFF3CT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=364, version=2, score=0.0, payload={'parent_asin': 'B0BR33XH8D'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=448, version=2, score=0.0, payload={'parent_asin': 'B0B45VPMT4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=305, version=2, score=0.0, payload={'parent_asin': 'B0B3GLJSFY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=229, version=2, score=0.0, payload={'parent_asin': 'B09Y39SFFL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=452, version=2, score=0.0, payload={'parent_asin': 'B0BHWK4T9J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=204, version=2, score=0.0, payload={'parent_asin': 'B09WR4KR4X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=289, version=2, score=0.0, payload={'parent_asin': 'B0C7492QYK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=80, version=2, score=0.0, payload={'parent_asin': 'B0BZQ5YKKY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=473, version=2, score=0.0, payload={'parent_asin': 'B09T7B55W3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=490, version=2, score=0.0, payload={'parent_asin': 'B09WDJ1NNB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=71, version=2, score=0.0, payload={'parent_asin': 'B0BPS9F24C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=328, version=2, score=0.0, payload={'parent_asin': 'B0B1TP23DX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=300, version=2, score=0.0, payload={'parent_asin': 'B09W9DV8PX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=368, version=2, score=0.0, payload={'parent_asin': 'B0BLJXPRL9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=270, version=2, score=0.0, payload={'parent_asin': 'B0BBG6P5SM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=410, version=2, score=0.0, payload={'parent_asin': 'B0BG55JZ1T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=99, version=2, score=0.0, payload={'parent_asin': 'B0BN8Q1Z9S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=391, version=2, score=0.0, payload={'parent_asin': 'B0BJZV7QVF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=261, version=2, score=0.0, payload={'parent_asin': 'B0BTSXW6NX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=491, version=2, score=0.0, payload={'parent_asin': 'B09T6N7TPS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=74, version=2, score=0.0, payload={'parent_asin': 'B0C3XYD574'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=367, version=2, score=0.0, payload={'parent_asin': 'B08VZ2X1H9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=478, version=2, score=0.0, payload={'parent_asin': 'B0B1ZJPY3K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=342, version=2, score=0.0, payload={'parent_asin': 'B0CDWZPRF2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=167, version=2, score=0.0, payload={'parent_asin': 'B0B8ZHF99W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=21, version=2, score=0.0, payload={'parent_asin': 'B0CBMPG524'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2, version=2, score=0.0, payload={'parent_asin': 'B0B96LV4C5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=128, version=2, score=0.0, payload={'parent_asin': 'B0BJJYFRLF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=432, version=2, score=0.0, payload={'parent_asin': 'B0B7MCLH1Y'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=87, version=2, score=0.0, payload={'parent_asin': 'B0BFDH4NX1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=245, version=2, score=0.0, payload={'parent_asin': 'B09V7MDRZ1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=53, version=2, score=0.0, payload={'parent_asin': 'B0B68DHY1J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=485, version=2, score=0.0, payload={'parent_asin': 'B0B5TJJTPY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=263, version=2, score=0.0, payload={'parent_asin': 'B09RKH6ST3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=255, version=2, score=0.0, payload={'parent_asin': 'B09KZK1494'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=474, version=2, score=0.0, payload={'parent_asin': 'B09QPH2GN3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=209, version=2, score=0.0, payload={'parent_asin': 'B09YRG3BYM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=65, version=2, score=0.0, payload={'parent_asin': 'B09XDNPQHZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=165, version=2, score=0.0, payload={'parent_asin': 'B0BKG66J4N'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=237, version=2, score=0.0, payload={'parent_asin': 'B09FFFSH25'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=162, version=2, score=0.0, payload={'parent_asin': 'B09YL52R4H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=416, version=2, score=0.0, payload={'parent_asin': 'B09Q5W9HPQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=251, version=2, score=0.0, payload={'parent_asin': 'B0BJ1MG9JL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=307, version=2, score=0.0, payload={'parent_asin': 'B09YRMGZDS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=93, version=2, score=0.0, payload={'parent_asin': 'B099K711GD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=34, version=2, score=0.0, payload={'parent_asin': 'B0BNHVLF7G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=178, version=2, score=0.0, payload={'parent_asin': 'B0C5CLD1HF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=143, version=2, score=0.0, payload={'parent_asin': 'B0C37GVWBP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=117, version=2, score=0.0, payload={'parent_asin': 'B0BQYN54PZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=177, version=2, score=0.0, payload={'parent_asin': 'B0BML99MQ3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=107, version=2, score=0.0, payload={'parent_asin': 'B0C7HFJR2K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=226, version=2, score=0.0, payload={'parent_asin': 'B09SFN9NRX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=124, version=2, score=0.0, payload={'parent_asin': 'B09Q345B29'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=219, version=2, score=0.0, payload={'parent_asin': 'B0BTD88265'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=248, version=2, score=0.0, payload={'parent_asin': 'B09R64LPCG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=327, version=2, score=0.0, payload={'parent_asin': 'B0CCC6PRK8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=61, version=2, score=0.0, payload={'parent_asin': 'B0BXRSFB93'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=78, version=2, score=0.0, payload={'parent_asin': 'B0BCCCNHD8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=295, version=2, score=0.0, payload={'parent_asin': 'B0B61Z8LKM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=181, version=2, score=0.0, payload={'parent_asin': 'B0CFG8BS2G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=90, version=2, score=0.0, payload={'parent_asin': 'B0BBM919DP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=222, version=2, score=0.0, payload={'parent_asin': 'B0B5W3J227'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=114, version=2, score=0.0, payload={'parent_asin': 'B0CJ66R5H2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=397, version=2, score=0.0, payload={'parent_asin': 'B09STGSRW2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=439, version=2, score=0.0, payload={'parent_asin': 'B08QS12HXF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=494, version=2, score=0.0, payload={'parent_asin': 'B09JZCPP87'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=101, version=2, score=0.0, payload={'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=174, version=2, score=0.0, payload={'parent_asin': 'B09ZJ7T3HL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=365, version=2, score=0.0, payload={'parent_asin': 'B0BVZ47N6N'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=221, version=2, score=0.0, payload={'parent_asin': 'B0C378ZL2K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=320, version=2, score=0.0, payload={'parent_asin': 'B0BF4STLSR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=239, version=2, score=0.0, payload={'parent_asin': 'B0BWXH2QS8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=471, version=2, score=0.0, payload={'parent_asin': 'B0C78B1BTB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=346, version=2, score=0.0, payload={'parent_asin': 'B0BFBJFKFB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=301, version=2, score=0.0, payload={'parent_asin': 'B0B3XZG67C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=445, version=2, score=0.0, payload={'parent_asin': 'B0BP7SCB2G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=318, version=2, score=0.0, payload={'parent_asin': 'B0BKYC6DTH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=277, version=2, score=0.0, payload={'parent_asin': 'B0CCW5D1NQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=285, version=2, score=0.0, payload={'parent_asin': 'B096G85CLH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=43, version=2, score=0.0, payload={'parent_asin': 'B0BGDQLZD2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=314, version=2, score=0.0, payload={'parent_asin': 'B09ZKN8YWH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=73, version=2, score=0.0, payload={'parent_asin': 'B0B8G6QW6X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=18, version=2, score=0.0, payload={'parent_asin': 'B08BX2L8F2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=351, version=2, score=0.0, payload={'parent_asin': 'B09PG1ZTH2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=79, version=2, score=0.0, payload={'parent_asin': 'B09GNF94GQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=187, version=2, score=0.0, payload={'parent_asin': 'B0BWDRP69M'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=62, version=2, score=0.0, payload={'parent_asin': 'B09MFM19SV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=366, version=2, score=0.0, payload={'parent_asin': 'B09R1WB2S5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=429, version=2, score=0.0, payload={'parent_asin': 'B0BTYMPPJC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=299, version=2, score=0.0, payload={'parent_asin': 'B0BGRL2618'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=483, version=2, score=0.0, payload={'parent_asin': 'B0C2C87FW3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=233, version=2, score=0.0, payload={'parent_asin': 'B0828S2KMV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=150, version=2, score=0.0, payload={'parent_asin': 'B0B934RS5N'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=196, version=2, score=0.0, payload={'parent_asin': 'B0CG657TNR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=354, version=2, score=0.0, payload={'parent_asin': 'B0BJTBFY5B'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=308, version=2, score=0.0, payload={'parent_asin': 'B09V193NLY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=477, version=2, score=0.0, payload={'parent_asin': 'B09PYKX76X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=472, version=2, score=0.0, payload={'parent_asin': 'B0B9RGGXC2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=404, version=2, score=0.0, payload={'parent_asin': 'B09TNRTPNW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=268, version=2, score=0.0, payload={'parent_asin': 'B0B7ML1ZGV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=159, version=2, score=0.0, payload={'parent_asin': 'B09XXW175L'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=339, version=2, score=0.0, payload={'parent_asin': 'B0BK957165'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=56, version=2, score=0.0, payload={'parent_asin': 'B0BK14FQMQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=145, version=2, score=0.0, payload={'parent_asin': 'B09YPWNBKZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=304, version=2, score=0.0, payload={'parent_asin': 'B09VL3V6CG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=358, version=2, score=0.0, payload={'parent_asin': 'B0BZW8ZLNQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=361, version=2, score=0.0, payload={'parent_asin': 'B09LH466KZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=203, version=2, score=0.0, payload={'parent_asin': 'B0BKQCC73S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=152, version=2, score=0.0, payload={'parent_asin': 'B09V18BFYL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=402, version=2, score=0.0, payload={'parent_asin': 'B09VNTHQ8B'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=425, version=2, score=0.0, payload={'parent_asin': 'B0BN48FNT5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=431, version=2, score=0.0, payload={'parent_asin': 'B0C7K8XHQF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=41, version=2, score=0.0, payload={'parent_asin': 'B08BR9X387'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=496, version=2, score=0.0, payload={'parent_asin': 'B0BZVHY74B'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=284, version=2, score=0.0, payload={'parent_asin': 'B0BSF9NZ3V'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=100, version=2, score=0.0, payload={'parent_asin': 'B0BBPVCFW7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=30, version=2, score=0.0, payload={'parent_asin': 'B0B2JJJFCD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=338, version=2, score=0.0, payload={'parent_asin': 'B0BLSDHWX8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=121, version=2, score=0.0, payload={'parent_asin': 'B0C5J4S25S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=215, version=2, score=0.0, payload={'parent_asin': 'B09T6XLV7C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=287, version=2, score=0.0, payload={'parent_asin': 'B09QZSHCKS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=151, version=2, score=0.0, payload={'parent_asin': 'B09TD2WR6H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=372, version=2, score=0.0, payload={'parent_asin': 'B09ZD9GRQ1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=194, version=2, score=0.0, payload={'parent_asin': 'B0B1GXQ78F'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=369, version=2, score=0.0, payload={'parent_asin': 'B0B8S4D469'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=279, version=2, score=0.0, payload={'parent_asin': 'B09Q3DH7V3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=415, version=2, score=0.0, payload={'parent_asin': 'B0C8CKSLZC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3, version=2, score=0.0, payload={'parent_asin': 'B0BZ5R7CVP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=213, version=2, score=0.0, payload={'parent_asin': 'B0C69MM2TP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=24, version=2, score=0.0, payload={'parent_asin': 'B0BS15TRJ3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=183, version=2, score=0.0, payload={'parent_asin': 'B09Y5WB2MP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=444, version=2, score=0.0, payload={'parent_asin': 'B0BKZ7D2F3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=95, version=2, score=0.0, payload={'parent_asin': 'B09MF44Q7C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=82, version=2, score=0.0, payload={'parent_asin': 'B09CCL371W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=106, version=2, score=0.0, payload={'parent_asin': 'B0B65DXSCJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=108, version=2, score=0.0, payload={'parent_asin': 'B0BGMYY12Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=42, version=2, score=0.0, payload={'parent_asin': 'B0CH6P8DYF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=208, version=2, score=0.0, payload={'parent_asin': 'B0BY1KPWRY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=83, version=2, score=0.0, payload={'parent_asin': 'B0C7Q3X76Q'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=138, version=2, score=0.0, payload={'parent_asin': 'B0BYSRTQNQ'}, vector=None, shard_key=None, order_value=None),

In [7]:
parent_asin_list = [item.payload["parent_asin"] for item in payload.points]

In [8]:
parent_asin_list

['B0BFGXRMJN',
 'B09SYSRBLC',
 'B09Z2NG36C',
 'B09XCJZKSR',
 'B09ZPMPNVH',
 'B0CGHVQ4M3',
 'B0C3X7JK7R',
 'B09VDNKL4G',
 'B0BGJ2TDXV',
 'B0BHSPB4JL',
 'B0BP68QCZ2',
 'B09TR8VXGL',
 'B0CGM29ZL7',
 'B0C9XFF3CT',
 'B0BR33XH8D',
 'B0B45VPMT4',
 'B0B3GLJSFY',
 'B09Y39SFFL',
 'B0BHWK4T9J',
 'B09WR4KR4X',
 'B0C7492QYK',
 'B0BZQ5YKKY',
 'B09T7B55W3',
 'B09WDJ1NNB',
 'B0BPS9F24C',
 'B0B1TP23DX',
 'B09W9DV8PX',
 'B0BLJXPRL9',
 'B0BBG6P5SM',
 'B0BG55JZ1T',
 'B0BN8Q1Z9S',
 'B0BJZV7QVF',
 'B0BTSXW6NX',
 'B09T6N7TPS',
 'B0C3XYD574',
 'B08VZ2X1H9',
 'B0B1ZJPY3K',
 'B0CDWZPRF2',
 'B0B8ZHF99W',
 'B0CBMPG524',
 'B0B96LV4C5',
 'B0BJJYFRLF',
 'B0B7MCLH1Y',
 'B0BFDH4NX1',
 'B09V7MDRZ1',
 'B0B68DHY1J',
 'B0B5TJJTPY',
 'B09RKH6ST3',
 'B09KZK1494',
 'B09QPH2GN3',
 'B09YRG3BYM',
 'B09XDNPQHZ',
 'B0BKG66J4N',
 'B09FFFSH25',
 'B09YL52R4H',
 'B09Q5W9HPQ',
 'B0BJ1MG9JL',
 'B09YRMGZDS',
 'B099K711GD',
 'B0BNHVLF7G',
 'B0C5CLD1HF',
 'B0C37GVWBP',
 'B0BQYN54PZ',
 'B0BML99MQ3',
 'B0C7HFJR2K',
 'B09SFN9NRX',
 'B09Q345B29',
 'B0BTD88265',
 'B09R64LPCG',
 'B0CCC6PRK8',
 'B0BXRSFB93',
 'B0BCCCNHD8',
 'B0B61Z8LKM',
 'B0CFG8BS2G',
 'B0BBM919DP',
 'B0B5W3J227',
 'B0CJ66R5H2',
 'B09STGSRW2',
 'B08QS12HXF',
 'B09JZCPP87',
 'B0BWVD7KZG',
 'B09ZJ7T3HL',
 'B0BVZ47N6N',
 'B0C378ZL2K',
 'B0BF4STLSR',
 'B0BWXH2QS8',
 'B0C78B1BTB',
 'B0BFBJFKFB',
 'B0B3XZG67C',
 'B0BP7SCB2G',
 'B0BKYC6DTH',
 'B0CCW5D1NQ',
 'B096G85CLH',
 'B0BGDQLZD2',
 'B09ZKN8YWH',
 'B0B8G6QW6X',
 'B08BX2L8F2',
 'B09PG1ZTH2',
 'B09GNF94GQ',
 'B0BWDRP69M',
 'B09MFM19SV',
 'B09R1WB2S5',
 'B0BTYMPPJC',
 'B0BGRL2618',
 'B0C2C87FW3',
 'B0828S2KMV',
 'B0B934RS5N',
 'B0CG657TNR',
 'B0BJTBFY5B',
 'B09V193NLY',
 'B09PYKX76X',
 'B0B9RGGXC2',
 'B09TNRTPNW',
 'B0B7ML1ZGV',
 'B09XXW175L',
 'B0BK957165',
 'B0BK14FQMQ',
 'B09YPWNBKZ',
 'B09VL3V6CG',
 'B0BZW8ZLNQ',
 'B09LH466KZ',
 'B0BKQCC73S',
 'B09V18BFYL',
 'B09VNTHQ8B',
 'B0BN48FNT5',
 'B0C7K8XHQF',
 'B08BR9X387',
 'B0BZVHY74B',
 'B0BSF9NZ3V',
 'B0BBPVCFW7',
 'B0B2JJJFCD',
 'B0BLSDHWX8',
 'B0C5J4S25S',
 'B09T6XLV7C',
 'B09QZSHCKS',
 'B09TD2WR6H',
 'B09ZD9GRQ1',
 'B0B1GXQ78F',
 'B0B8S4D469',
 'B09Q3DH7V3',
 'B0C8CKSLZC',
 'B0BZ5R7CVP',
 'B0C69MM2TP',
 'B0BS15TRJ3',
 'B09Y5WB2MP',
 'B0BKZ7D2F3',
 'B09MF44Q7C',
 'B09CCL371W',
 'B0B65DXSCJ',
 'B0BGMYY12Z',
 'B0CH6P8DYF',
 'B0BY1KPWRY',
 'B0C7Q3X76Q',
 'B0BYSRTQNQ',
 'B0BY9QNXFH',
 'B0BTPG4XHH',
 'B0CD43HNTS',
 'B0BVTCG71C',
 'B0BQ6FH49Y',
 'B0BDRD5TRX',
 'B0C7R18CG3',
 'B08P6B8GR9',
 'B0BBJBZPFS',
 'B0BL2CZSHT',
 'B0B8NVNQKX',
 'B0B6RC686L',
 'B0BMG6TZ8F',
 'B0B9FTVL58',
 'B0BXXSHLTJ',
 'B0BTP9YFT6',
 'B0B5HMT1YW',
 'B0C48WYVBQ',
 'B0BX85LFW8',
 'B0BJ326LNW',
 'B0C65RMTNV',
 'B09PRK49JH',
 'B09SSZNWQD',
 'B0C142QS8X',
 'B0CB3VSWWB',
 'B0CDLCLTMT',
 'B0C65TKK8V',
 'B09WTW1H9D',
 'B09XV39FHL',
 'B09XN72MP6',
 'B0B7495RL6',
 'B0B7DJ6ZZ4',
 'B0BW3GT2YJ',
 'B0CG68ZMFV',
 'B09R4Y2HKY',
 'B0BFDLTRGX',
 'B0B56CRXDC',
 'B0B3HKDCP4',
 'B0BDF9M8SX',
 'B0C1RTRF9G',
 'B0C5WGFL2N',
 'B0BV6PWVCG',
 'B0B8CKD3TN',
 'B0C13NF5JC',
 'B0B2914WPG',
 'B0BG5L2YLC',
 'B0BG2SKNPM',
 'B09QKT9QZ6',
 'B0B97GBHXB',
 'B0B3WVTMWF',
 'B0CCRP8LRQ',
 'B0BGLRMPQD',
 'B0C5MBLHD2',
 'B09Z2HHG4L',
 'B0BMWQWFTX',
 'B0BBPTY7Y7',
 'B0C3VRH58B',
 'B09RWW247J',
 'B0BB1YKXL1',
 'B0BGX5J2DF',
 'B0C3QYJZN5',
 'B0BSGDCVND',
 'B0BF98MTY9',
 'B09SPBM7D3',
 'B08V8R6JML',
 'B0B245T2KX',
 'B0B17SD56J',
 'B09NS335ZF',
 'B0C7CPL179',
 'B0BJW1SRG5',
 'B0C5XHF3XD',
 'B0C69FCWN4',
 'B0B3QLP8XR',
 'B09T6983Y1',
 'B0BKSXQ9D3',
 'B0C6K1GQCF',
 'B0BNKWKMHY',
 'B0BMVR2MVC',
 'B09VF5ZCRC',
 'B0C6Y8Q2S1',
 'B09MWJJ3RW',
 'B0B2C5RDV6',
 'B0C6PGF8BV',
 'B0C595QFS9',
 'B0BMQP624X',
 'B0C7GS19F2',
 'B0BZ3J6XD6',
 'B09QS2D9TZ',
 'B0BB2V7DCR',
 'B0CJ8SDWZP',
 'B0BY2ZBRZD',
 'B0BQ6P583M',
 'B0BXRWX9RN',
 'B09W897L3T',
 'B09VB5M3L5',
 'B0BDQSK1JG',
 'B0BLV7YH2W',
 'B09WR2KXFR',
 'B09WTM778R',
 'B0B6PGXXK8',
 'B0BBWLP9KV',
 'B0B9ZX2DCJ',
 'B0BM9MTSH2',
 'B0BJDVXB6T',
 'B0B4B45CYV',
 'B0C1NDPD5L',
 'B0B55TZLBR',
 'B0BJK7YRCB',
 'B0BWN4MYDK',
 'B09ZPV8WBV',
 'B0BR9135RC',
 'B09V4DS551',
 'B0B11P5XHV',
 'B0BC78N85F',
 'B09WCFC5D9',
 'B0C9T5H9F2',
 'B0C3XS6N81',
 'B0C1YD8V9F',
 'B0C373P4M7',
 'B096XB5Q1T',
 'B0BH4VZKQ5',
 'B09YBR36CV',
 'B0C772GZRF',
 'B0C7RF6YTR',
 'B0BLYCBGMF',
 'B09QLKN43H',
 'B09L9FFC6P',
 'B07TSS65YZ',
 'B0BWTWKTVR',
 'B0B9MPGXDL',
 'B0C64SQ23S',
 'B0838HWTZW',
 'B0CB1MT9WD',
 'B09YJ2867L',
 'B0B28RMNM2',
 'B09Y39DSWR',
 'B0C8592NWX',
 'B099WCCWC5',
 'B0BT6SCPW7',
 'B09B9MSWL3',
 'B0B4V7XW21',
 'B0BSS319BG',
 'B0C5LYL14Z',
 'B0BVH2K81J',
 'B09MRM2NGG',
 'B0BGPPX7DC',
 'B09RJP7YM2',
 'B09XX3J786',
 'B09YMRF553',
 'B0BH3X1HGH',
 'B0BJS6CXDN',
 'B0C64P1WX4',
 'B0BHRVW8SW',
 'B0BMQDTQJL',
 'B0B6P9SM9S',
 'B0B6KMRN9B',
 'B09MRBYHKG',
 'B0BFVVFJG3',
 'B09VGH2LJC',
 'B09ZV2XJ65',
 'B09T7YT8HC',
 'B0BR8Q2PXN',
 'B0C3CL7VP4',
 'B0B8BY5HCG',
 'B0CG8J2X6X',
 'B0CHN3BSQM',
 'B0C6L1RC6Y',
 'B09TDJBZ7X',
 'B0BKPB2YQ9',
 'B0BVPZNQBG',
 'B09Q5M5W8R',
 'B0B67ZFRPC',
 'B0B3T848VM',
 'B0BNWNSL1J',
 'B0B8DJYF59',
 'B0BN7WWH63',
 'B0B2V9P3K4',
 'B09QGNB537',
 'B09LVX3XW2',
 'B09DK8NK6G',
 'B0C272636P',
 'B0BNVKS9WH',
 'B09NBS9DS6',
 'B0BYSY8NXV',
 'B0BP1YXF3R',
 'B0B8TVYY2T',
 'B0BF18F6R7',
 'B0CC61QC4J',
 'B0BTKWY6XG',
 'B0C8PFRRFC',
 'B0BMM5QQST',
 'B0BT9SLRXR',
 'B09Y2HK4N5',
 'B0BYH466CM',
 'B08LZQCHSF',
 'B0BB7LXFZF',
 'B0BLCMRKR4',
 'B09Q9C6MG1',
 'B0BB7CYXXW',
 'B0C936DH1R',
 'B09XCKYXR8',
 'B0B5W5NKKN',
 'B0BZB3K3M5',
 'B0BHW4BP6X',
 'B09V9P7Z1T',
 'B09NNDZLV2',
 'B0BYSG5GX2',
 'B0BZP7BM9R',
 'B0B1MZT835',
 'B09VGS8TSH',
 'B09PYFMTBF',
 'B0B5SWJXZV',
 'B09TT8MQ7M',
 'B0BN7TWMXJ',
 'B0BNPVBZPG',
 'B0B99GGZ66',
 'B0BGR8FS29',
 'B09YTGFYZK',
 'B09T2J1LSB',
 'B0CF57H28T',
 'B0BVVRSHQ5',
 'B0BY1ZYQPQ',
 'B08L5ZW5DK',
 'B07TF5QD6B',
 'B09V7LNPC3',
 'B0BYKDMMVJ',
 'B0BT344Q4K',
 'B09V12Y68C',
 'B09MT7567J',
 'B0BQ6PVB8S',
 'B09R8YGSLN',
 'B0C4GW8CCC',
 'B09TKFDCV5',
 'B09X1B9KTF',
 'B0B39PFLSW',
 'B0BWTVXQ62',
 'B09Y77N1T2',
 'B09YX644CY',
 'B0B1QNXFBD',
 'B0BZVSL3JR',
 'B09PYN3P4B',
 'B0B31H2TBX',
 'B09XX27FH2',
 'B0B2NQS9K3',
 'B09PFSVK44',
 'B0BZT27M7J',
 'B0C5WYSL3B',
 'B09YLWM325',
 'B0BN1K6P1S',
 'B0C4DBSWGW',
 'B0B1MPKCS8',
 'B09D3GRST4',
 'B0BB2Q387X',
 'B0B97LCTXZ',
 'B09V5D3B17',
 'B0BHDX2GDZ',
 'B0C34FJG3P',
 'B0C9V31PL1',
 'B0CF1WM24K',
 'B0B8NCR19L',
 'B09TNXY54Y',
 'B0CFFGT7RM',
 'B0BFRLNTRR',
 'B09TTBWHN5',
 'B0BN5N31Q5',
 'B0B913XQX7',
 'B0BNMWHLRK',
 'B0BN3GHSTC',
 'B09GNFDH9M',
 'B0B14HTZ59',
 'B09SHPX1FQ',
 'B0BB7S4T1M',
 'B09TP3SZ7C',
 'B0B62LR2YT',
 'B0B6V8THVX',
 'B09PQ97H3G',
 'B0B6PKDSMN',
 'B0BXNP7DYW',
 'B09R1TMXR3',
 'B0BTDFY2DN',
 'B0BYYLJRHT',
 'B09TF5WK26',
 'B0C78HVVL2',
 'B0C16S18PX',
 'B09TKVV8MJ',
 'B09Y95BMKX',
 'B09W5RJ1LY',
 'B0BVZP14HM',
 'B0BBY5TGTM',
 'B07YZHJRCV',
 'B0C435BRST',
 'B09RV6KSMH',
 'B0BJQ7FC9S',
 'B07MZK432D',
 'B09QPQZMMN',
 'B08L4MT463',
 'B0B4915S57',
 'B09ZL3PXF2',
 'B09W5KD1SD',
 'B0BFPZGYLD',
 'B09X9QZDR4',
 'B0BP9Z159S',
 'B0BM79FR3B',
 'B0BD4RWZLZ',
 'B0BGQC1K6R',
 'B09SD9NF6N',
 'B0BQCG3T3B',
 'B08D8Z9LPW',
 'B08CGM6Y1J',
 'B0BSRGYNWV',
 'B08P1T8R46',
 'B0B8TH21GK',
 'B0BMG766L1',
 'B0CB7J8KN4',
 'B0BL3YGC62',
 'B09QJRYJW4',
 'B0BNN776VN',
 'B0B3MMP22L',
 'B09MPNX216',
 'B0BTDJ6FBR',
 'B09ZQBXVWF',
 'B0BPNNV5NW',
 'B0BJ1SLJH1',
 'B0BR8NKQ12',
 'B0B7NMSTT9',
 'B09WVHZ4X8',
 'B0BJK3V3P4',
 'B09R6H1Z6H',
 'B0B4N1D73R',
 'B0BF983MDW',
 'B09Q61G298',
 'B0C4W4XMVZ',
 'B0C6LCJ95V',
 'B09SHNKDBC',
 'B09X2W94RP',
 'B0BTYQ7VVM',
 'B0B2P18Z31',
 'B0B2KTG62P',
 'B09PN99MN9',
 'B09SKRR2MF',
 'B0BHT65J5C',
 'B0BXQ4R99F',
 'B0BC426455',
 'B0BRXZDBXZ',
 'B0BKKP997X',
 'B0B9JF64DM']

In [9]:
len(parent_asin_list)

500

### Load Amazon Reviews Dataset

In [12]:
df_reviews = pd.read_json("../../data/Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [13]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,1,love it but ... spoke too soon,UPDATE: OMGGG this thing SKIPSSSS and crackle...,[],B07QK824QM,B0CBWV3Q8B,AHGAOIZVODNHYMNCBV4DECZH42UQ,2019-12-05 17:36:37.115,4,True
1,4,Nixplay 10.1 touch screen digital picture frame,I purchased this digital frame on a treasure t...,[],B096DQF21Z,B0BNXXNBB4,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-29 06:52:30.702,19,True
2,3,Not For Larger Wrists,It's been a while since I had gotten a new ban...,[{'small_image_url': 'https://m.media-amazon.c...,B09GVKXFRQ,B0B19SL9TF,AHV6QCNBJNSGLATP56JAWJ3C4G2A,2021-11-18 17:02:02.035,1,False
3,5,Beautifully Made,This is another beautifully made bag from Vera...,[],B08TPSL1FW,B0B85V929L,AHV6QCNBJNSGLATP56JAWJ3C4G2A,2021-07-07 22:44:26.631,0,False
4,5,So easy to use,Overall I am enjoying my new Skylight frame. ...,[],B01N7ENHO6,B0BV3FZ8KY,AFIDB4NPTG3E7KHCX7BUO4WDE6LQ,2019-12-31 20:59:55.824,0,True

In [14]:
len(df_reviews)

96850

In [15]:
df_reviews_sample = df_reviews[df_reviews["parent_asin"].isin(parent_asin_list)]

In [16]:
len(df_reviews_sample)

3943

### Define functions to preprocess reviews data

In [17]:
def preprocess_reviews_data(row):
    return f"{row['title']} {row['text']}"

In [18]:
encoding = tiktoken.encoding_for_model("text-embedding-3-small")

In [19]:
encoding.encode("Can I gert some earphones?")

[6854, 358, 342, 531, 1063, 2487, 17144, 30]

In [20]:
def token_count(row, model="text-embedding-3-small"):

    encoding = tiktoken.encoding_for_model(model)
    return len(encoding.encode(row["preprocessed_data"]))

In [21]:
df_reviews_sample["preprocessed_data"] = df_reviews_sample.apply(preprocess_reviews_data, axis=1)

/var/folders/hd/mwwk_4zs7blcj6tc0ycm9t5c0000gn/T/ipykernel_2589/1882656165.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reviews_sample["preprocessed_data"] = df_reviews_sample.apply(preprocess_reviews_data, axis=1)

In [22]:
df_reviews_sample["preprocessed_data_token_count"] = df_reviews_sample.apply(token_count, axis=1)

/var/folders/hd/mwwk_4zs7blcj6tc0ycm9t5c0000gn/T/ipykernel_2589/1530805122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_reviews_sample["preprocessed_data_token_count"] = df_reviews_sample.apply(token_count, axis=1)

In [23]:
df_reviews_sample.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,preprocessed_data_token_count
17,5,Five Stars,Worked perfect and was no problem to set up th...,[],B003CFATNI,B0BJ1SLJH1,AE5PZITMWZJBPVKL7XXYUFBTITQA,2017-02-11 03:35:13.000,0,True,Five Stars Worked perfect and was no problem t...,20
29,5,Works Fine,"This card is very small, I was surprised when ...",[],B003CFATNI,B0BJ1SLJH1,AF6NMYYHILKNULG772IZLOFGYAAA,2013-02-24 05:02:21.000,2,True,"Works Fine This card is very small, I was surp...",44
105,5,Huge,Love it. Big and wide. Great clarity. I use it...,[],B09ZYTFX33,B0BMQP624X,AFOHEEK7Z7O37JDYNEMCZSBUZHYA,2022-09-22 20:52:44.420,1,True,Huge Love it. Big and wide. Great clarity. I u...,30
107,5,Does what it says its does,Works like a champ,[],B003CFATNI,B0BJ1SLJH1,AGUWDJXPNE4CB2AFX4YK76XZUHGQ,2019-10-09 04:45:31.060,0,True,Does what it says its does Works like a champ,10
120,5,Awesome,Works awesome! I have no complaints installed ...,[],B003CFATNI,B0BJ1SLJH1,AF3IOPFWELTFPZFYBKFWOJ3B6D7Q,2014-03-06 06:06:16.000,0,True,Awesome Works awesome! I have no complaints in...,27

In [24]:
len(df_reviews_sample)

3943

In [25]:
df_reviews_sample = df_reviews_sample[df_reviews_sample["preprocessed_data_token_count"] < 8192]

In [26]:
len(df_reviews_sample)

3943

In [27]:
total_tokens = df_reviews_sample["preprocessed_data_token_count"].sum()

In [28]:
total_tokens

np.int64(231141)

### Create a new Qdrant collection for reviews

In [29]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01-reviews",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

True

In [30]:
qdrant_client.create_payload_index(
    collection_name="Amazon-items-collection-01-reviews",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding functions

In [31]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=[text],
        model=model,
    )
    return response.data[0].embedding

In [32]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

### Embed the text and add additional fields to the payload of each vector for reviews

In [33]:
data_to_embed_reviews = df_reviews_sample[["preprocessed_data", "parent_asin"]].to_dict(orient="records")

In [34]:
data_to_embed_reviews

[{'preprocessed_data': 'Five Stars Worked perfect and was no problem to set up the drivers. Well worth the money.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Works Fine This card is very small, I was surprised when I saw it.  It uses a Realtek chip so windows had no problem recognizing it and I expect it to last for as long as I need it.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Huge Love it. Big and wide. Great clarity. I use it for work - email, spreadsheets, applications. Extra space improves productivity.',
  'parent_asin': 'B0BMQP624X'},
 {'preprocessed_data': 'Does what it says its does Works like a champ',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Awesome Works awesome! I have no complaints installed the card on my Win 7. It works incredibly fast and moves files fast LOVE it',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'No Mac Address This card did not come with a MAC address and would not take a static IP or get one from DHCP.  Returned.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Great noise cancellation and bass, clear sound, ok treble These headphones offer crisp sound with deep bass capability, and decent treble that can *sometimes sound slightly tinny but isn’t a big deal. The noise cancellation works great on a wide range of white noise, from the fridge or dishwasher to airplane engines. The fit is comfortable for short or long use, and the package includes a travel bag. Important note on cables: DO NOT LOSE THE AUX CABLE—it converts the usbc to an auxiliary standard headphone/sound jack. THERE IS NO STANDARD AUX SOUND SOUND JACK ON THE HEADPHONES. Just remember your cable and it will be fine, but it only has one port for both charging and listening. Great headphones!',
  'parent_asin': 'B0B8NCR19L'},
 {'preprocessed_data': "Improved Picture! This HDMI cord works really well. It improved the picture on our TV quite a bit on the high definition stations. It's light weight and cloth covered. A Great Buy!",
  'parent_asin': 'B0C595QFS9'},
 {'preprocessed_data': "Great features. Easy, intuitive setup. Impressive sound. I purchased the projector primarily for movie night with the family. Once unboxed, I connected to Wi-Fi and was watching videos in less than 5 minutes. With Bluetooth turned on, I easily connected to my Bluetooth soundbar. The screen mirroring feature works well; however, you can't mirror streaming services like Netflix and Hulu due to copyright restrictions. I plugged a Fire Stick into one of the HDMI ports and was able to use the full functionality of the Fire Stick and watched Netflix flawlessly. Seems like a great projector with impressive features for the price.",
  'parent_asin': 'B09MFM19SV'},
 {'preprocessed_data': 'So far so good! Have had this monitor for a month now and it is great! Makes working from home much more pleasurable.',
  'parent_asin': 'B0BMQP624X'},
 {'preprocessed_data': 'Easy! Great!', 'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Works great. Compatible with Windows 10. I bought this when a Windows 10 update caused issues with my built in NIC card in my Dell XPS 8000. The card was easy to install and works great with older dell running Windows 10.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': "Just OK. These cameras are OK -- just not as good as the Night Owl cameras that came with the security system.  Lower resolution and can be grainy at times.  Of course, they're not $100 cameras either.",
  'parent_asin': 'B0BYSG5GX2'},
 {'preprocessed_data': 'Sturdy This is a very thick and heavy duty cord. It came well packaged and had little coverings to put over the ends to keep dust from building up while not in use.',
  'parent_asin': 'B0C595QFS9'},
 {'preprocessed_data': "I am really liking this headset, surprised by the quality of sound, noise cancelling, and comfort In my work I need long periods of quiet. I’ve done what I can to deal with a lack of quiet these last two years, between my wife working at home and the neighborhood seeing far more people at home. I’ve tried a few things, but in many ways had to sacrifice and learn to deal with the sound. For several months I was working from midnight till 3 or 4 am to get some of my work done. So I started to think about going back to headphones. I’ve previously owned a set of a well known, expensive brand that was good - well, great sound, but they were big and got to be far too hot on my head, especially over time. So I ended up getting rid of those. I still wear a set of those that sit on the outside of my ears for sound - which is outstanding - but they don’t always cover enough noise as they were designed to allow the athletes who wear them to actually hear sound around them. So....<br /><br />I was thinking what I might do again. I had the chance to get these Ankbit Hybrid Active Noise Cancelling Headphones, but went in knowing they too might be too hot on my head after awhile. I figured I’d at least get some work done in a few hours each day.... but would they be enough?<br /><br />I should also mention, I have a lifelong issue with my ears that causes me to feel the pressure (think airplanes and storms) in such a way it can bother my head. The other reason I got rid of those expensive well know headphones was that they sat so securely on my head, the pressure was too much for my head. I again, could only wear them for so long before I had to take them off.<br /><br />So, these Ankbit Hybrid Active Noise Cancelling Headphones?<br />So far I really like them - a lot!<br />I’ve been wearing them every day for at least a few hours and getting work done. It has taken a bit of time to adjust, but what I am experiencing has been helpful and I am glad to have them.<br /><br />The box they come in includes the headset, a bag, and needed cords.<br /><br />The cords are easy to use, but I would say, it would be nice if the cord for charging were longer. I mean, this thing is SHORT! Where I could normally set an item off to the side with the cord reaching, I now have to set these headsets directly in front of the plug, meaning plugging in other things is difficult. So that would be one improved this set could use.<br /><br />The bag is great. It is black, nice material, and holds the headset well. Glad to have it.<br /><br />The Ankbit Hybrid Active Noise Cancelling Headphones themselves are surprisingly great. I don’t know why it surprises me, other than I had that expensive pair in the past - which was outstanding - and I like these as much - in some ways, more (think ear discomfort and overheating).<br /><br />1. The set is comfortable with the ear covers nice and soft on my ears. They are enough to sit well, hold in the sound (my wife has not complained about any sound bleed), and work as far as noise canceling. ** I'll come back to this in a minute. But I find the Ankbit Hybrid Active Noise Cancelling Headphones to be very comfortable. If I had one “complaint” it’s that they are slightly large. I have a large head on which I wear large hats. However, even I find the top of this to be a bit larger than my head - which tells me someone with a smaller head than mine might have an issue with the size of these. They do fit, and the ears sit directly on my ears, but I can tell it’s just on my ears. It is comfortable, but something I take note of.<br /><br />2. There is no (noticeable) pressure build up. Where my previous set caused such pressure that I’d have to take them off at least twice an hour, I’ve never had to take these off and have worn them up to 3 hours at a time - and could go longer.<br /><br />3. ** The noise reduction works. We tested this the first day - including matching to another work style head set I got to also try and block the noise - the kind used on construction sites and the like - and this Ankbit Hybrid Active Noise Cancelling Headphones worked as well or perhaps better than that set. While that set has no music or sound to it and this does, both blocked my wife’s talking and yelling within 2 - 3 feet of me to the point that I could barely hear her. This Ankbit Hybrid Active Noise Cancelling Headphones offers the music as a way to add to the options - and I use an app to help if need be, with sounds such as white noise and thunderstorms. But in general, I prefer to be able to have no noise at all at times. With both the app sounds and no sound at all, I am able to block out MOST noise. I do add the app when my wife is working in the kitchen, which is behind my back where I’m working now she’s home. And the app takes care of the rest of the sound. But without it, I have great sound reduction and elimination.<br /><br />You can also turn this feature off and have “transparency” which allows you to hear background noise, incase you need to listen for the kids or a phone. It still. blocks the sound, gives you good internal sound with music, but you can hear outside sound better. It is like my other, outside the ear set when in this mode, so I do not use it - I have those for that type of sound. But it is available.<br /><br />4. The sound itself is excellent. I have listened to music and movies playing on these and both are outstanding. I truly love the sound and find it is full, rich, and well done. It’s a pleasant experience.<br /><br />5. The buttons for on/off, volume up/down, and transparency are at the side of the ear phone on the right side and 1. EASY to the point of frustration that I keep hitting them - usually turning it off - when trying to remove the headset,  and needing to learn how to not hit them and 2. easy to use overall. The four buttons are easy to adjust - I’m still getting use to which is which and not second guessing. The on/off is easy, but I’m really impressed with the volume up/down, which is in nice levels of degrees - not too much either way - and gives a great sound.<br /><br />I also discovered - the hard way - when you close the computer it’ll go off, but open and it’s back up and running. There are so many little things like that. I don’t know, maybe they are far more common than I know - I have not been a headset user for some time - but these are details that impress.<br /><br />Overall I really like this Ankbit Hybrid Active Noise Cancelling Headphones for my work and the quiet it provides, but for the sound I get when I’m listening to sounds to help me work, or even better, the music and movies that help keep me going throughout the day. I’m impressed and if this set lasts for a few years... it’ll be an outstanding find!",
  'parent_asin': 'B0B8NCR19L'},
 {'preprocessed_data': 'Excellent nic Easy to install and works great.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': "I like it DH recommended it based on his previous purchases of LG products.  I'm satisfied, and the Windows screen snap feature didn't require the installation of any special software to get the double screen effect.",
  'parent_asin': 'B0BMQP624X'},
 {'preprocessed_data': 'Excellent quality at a competitive price Links at a full gigabit and is capable of providing a full gig in each direction with my fiber connection.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Beautiful Beautiful art for my dining room. great quality and great price',
  'parent_asin': 'B0C7HFJR2K'},
 {'preprocessed_data': "after using the mini-cd that came with it to install the drivers it's worked like a charm not the plug n play... turn the machine off install and vola! after using the mini-cd that came with it to install the drivers it's worked like a charm. Easy upgrade options instead of replacing tons of parts just to get the 1000Mbps speed vs. 100.",
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Four Stars good stuff', 'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Good value I like amount of faces I can use from the app.  I also like that I can set it to vibrate when I get calls.  I do not use it for messaging.  Good value.',
  'parent_asin': 'B0BBPTY7Y7'},
 {'preprocessed_data': "Great for movie night! I got this screen to use with our projector for better viewing quality.  We originally planned to use a large blank wall in our great room or the vinyl privacy fence in the backyard to watch movies via the projector, but quickly realized that a projection screen was a must (lol).  The ultra smooth surface of this generously sized projector screen gives a crisp clear picture quality.  And the stand gives you the flexibility of using it indoors or outdoors.  It's quick and easy to set-up and take down.  Doesn't take up alot of storage space which is nice.  Overall, a quality made projection screen.  We look forward to many family movie nights to come!",
  'parent_asin': 'B0BKKP997X'},
 {'preprocessed_data': 'does NOT work with apple products Does NOT work for iPhone products. Only actual product bought from Apple will work with their products.<br />Don’t believe the lies, just fork over the money for the real deal and save yourself time and money AND frustration by not having to return these boogers after you don’t take this advice!😜',
  'parent_asin': 'B0CG68ZMFV'},
 {'preprocessed_data': 'Five Stars High quality!!',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': "Great little widescreen monitor I was looking for a smaller widescreen monitor to use as a 3rd monitor above my two main ones. I also have a shelf on the wall above my monitors so my space is limited. Based on the dimensions of this it would fit perfectly in the space and it did! I mostly use it for browsing and background TV while I work and its great for that.<br /><br />I'm not sure I would be happy with this as a main monitor because of the odd resolution, but as a secondary or tertiary monitor I think its fantastic! It was exactly what I wanted and has performed beautifully.",
  'parent_asin': 'B0BMQP624X'},
 {'preprocessed_data': 'Easily Installed and Worked My internet connection was lost on my XP video machine.  I tried updating the driver with no luck.  Purchased this card and a computer store installed it for me.  They also fixed my motherboard access so now I have two outlets working.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': "It's cheap. It's simple. It works. I took on a project where I recycled one of my PCs and turned it into a firewall/router for my home network. The only thing I was lacking for the project was a second gigabit Ethernet adapter. I've actually used quite a bit of TP-Link's networking gear in recent years, so I figured that I might as well give this inexpensive PCIE gigabit Ethernet card a shot.<br /><br />Long story short, the card works like a champ. It was easily detected by the firewall software that I used for the install, which is based on the BSD operating system. Since it easily autodetects in BSD I would assume that it works equally well with Linux. I did not bother testing it on a Windows installation, so you should check the manufacturer's specs to make sure that it works with whatever version of that operating system you happen to be using before buying.<br /><br />Autodetection of the card worked without a hitch and the card is now operating on my gigabit LAN at full duplex with no problems whatsoever. It's simple. It's cheap. It works. That is about the best I can say for any product.",
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'For kids Bought these for a flight to keep the grand kids entertained.  Worked out well.',
  'parent_asin': 'B0CG68ZMFV'},
 {'preprocessed_data': "Plug-n-play with multiple OS's Purchased for a friend who needed a simple drop-in card for his Win7 x64 machine. He was able to drop it right in, Windows automagically installed the drivers and he was back online in a matter of minutes. Based on searching for other cards, this one seemed to offer the best chipset and driver compatibility for the price.",
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Great product but no power output It does the basics and has all the basics you need to work from home. I don’t like controlling the buttons from under the screen. I don’t like the fact It doesn’t work well with my surface pro from work. I can’t use the wide screen on the surface pro. The speakers are good but not like the MacBook M1. My MacBook works great in wide screen and it was easy to step up. I had to get a docking station because the monitor had no power output to charge my MacBook. It will charge my iPhone. I have connect external adaports. I wish this came with more ports and a power output but I guess we get what we pay for. The size fits perfectly on my Micke desk from IKEA in my closet at home.',
  'parent_asin': 'B0BMQP624X'},
 {'preprocessed_data': "My main monitor I need two screens to do most of my work.  I was using my laptop and a much larger screen.  But I was getting tired of looking back and forth and seeing two different resolutions/sizes of the applications I use (I know, first world problem).  This ultrawide was a good price and the other monitor I have and really like is an LG, so I took a chance.  It's just what I needed.  Would I have liked a curved monitor?  Absolutely, but I also didn't want to pay $600 for it.  This does the job!  I have two browser sessions open on it at all times. The picture is very clear and bright.  The speakers also work well!  I don't do any gaming or anything with this, it's for work.<br /><br />I'm using the stand it came with.  It didn't take too long to put together and I can rotate the screen to the left and right.  It does not slant up or down at an angle, but you can easily choose a different height from within the stand.  I've never needed to rotate it vertically, but that's easy to do as well.  The monitor itself is very light, the stand is plenty secure.",
  'parent_asin': 'B0BMQP624X'},
 {'preprocessed_data': 'Good network card I bought this card because it was cheap but it also works really well. I got full gigabit speeds from this with no issues.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Five Stars Excellent! Love it!',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': "Too Tall for my needs I didn't realize this at first but just having a PCIe x1 slot doesn't mean it'll allow the case to close. This card sticks out about 3/4&#34; too high to close my case (note: this is a small form factor pfSense install)<br /><br />Not $$ enough to bother returning so I found a different one on Amazon that's only 1.5&#34; high and will hopefully fit<br /><br />Now what to do w this one?",
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': 'Seems to be working fine, I have more than double some network speeds ... Seems to be working fine, I have more than double some network speeds and now my bottleneck is the hard drives.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'preprocessed_data': "Comfortable, noise cancelling works These headphones were purchased for our 12 year old grandson for Christmas. He put them on immediately after opening them replacing the other headphones he already had. We stayed a week and he wore them every chance he could. He said he loved them, they were very soft and comfortable and the noise cancelling worked way better than his other headphones. We would recommend and will probably purchase again as soon as the next grandchild's birthday comes along.",
  'parent_asin': 'B0B8NCR19L'},
 {'preprocessed_data': "Nice new look for my fenix 5 This order arrived promptly, fit perfectly, and looks great.  It is genuine leather and a little stiff, as expected, at first--but quickly relaxed.  I like the subtle red stripe.  I haven't had it long enough to confidently comment on durability, but it seems rugged enough to last.  Strongly recommend!",
  'parent_asin': 'B09XV39FHL'},
 {'preprocessed_data': 'Good NIC for good price. Good inexpensive NIC to replace your dead motherboard or for a second network',
  'parent_asin': 'B0BJ1SLJH1'},

In [35]:
text_to_embed_reviews = [data["preprocessed_data"] for data in data_to_embed_reviews]

In [36]:
text_to_embed_reviews

['Five Stars Worked perfect and was no problem to set up the drivers. Well worth the money.',
 'Works Fine This card is very small, I was surprised when I saw it.  It uses a Realtek chip so windows had no problem recognizing it and I expect it to last for as long as I need it.',
 'Huge Love it. Big and wide. Great clarity. I use it for work - email, spreadsheets, applications. Extra space improves productivity.',
 'Does what it says its does Works like a champ',
 'Awesome Works awesome! I have no complaints installed the card on my Win 7. It works incredibly fast and moves files fast LOVE it',
 'No Mac Address This card did not come with a MAC address and would not take a static IP or get one from DHCP.  Returned.',
 'Great noise cancellation and bass, clear sound, ok treble These headphones offer crisp sound with deep bass capability, and decent treble that can *sometimes sound slightly tinny but isn’t a big deal. The noise cancellation works great on a wide range of white noise, from the fridge or dishwasher to airplane engines. The fit is comfortable for short or long use, and the package includes a travel bag. Important note on cables: DO NOT LOSE THE AUX CABLE—it converts the usbc to an auxiliary standard headphone/sound jack. THERE IS NO STANDARD AUX SOUND SOUND JACK ON THE HEADPHONES. Just remember your cable and it will be fine, but it only has one port for both charging and listening. Great headphones!',
 "Improved Picture! This HDMI cord works really well. It improved the picture on our TV quite a bit on the high definition stations. It's light weight and cloth covered. A Great Buy!",
 "Great features. Easy, intuitive setup. Impressive sound. I purchased the projector primarily for movie night with the family. Once unboxed, I connected to Wi-Fi and was watching videos in less than 5 minutes. With Bluetooth turned on, I easily connected to my Bluetooth soundbar. The screen mirroring feature works well; however, you can't mirror streaming services like Netflix and Hulu due to copyright restrictions. I plugged a Fire Stick into one of the HDMI ports and was able to use the full functionality of the Fire Stick and watched Netflix flawlessly. Seems like a great projector with impressive features for the price.",
 'So far so good! Have had this monitor for a month now and it is great! Makes working from home much more pleasurable.',
 'Easy! Great!',
 'Works great. Compatible with Windows 10. I bought this when a Windows 10 update caused issues with my built in NIC card in my Dell XPS 8000. The card was easy to install and works great with older dell running Windows 10.',
 "Just OK. These cameras are OK -- just not as good as the Night Owl cameras that came with the security system.  Lower resolution and can be grainy at times.  Of course, they're not $100 cameras either.",
 'Sturdy This is a very thick and heavy duty cord. It came well packaged and had little coverings to put over the ends to keep dust from building up while not in use.',
 "I am really liking this headset, surprised by the quality of sound, noise cancelling, and comfort In my work I need long periods of quiet. I’ve done what I can to deal with a lack of quiet these last two years, between my wife working at home and the neighborhood seeing far more people at home. I’ve tried a few things, but in many ways had to sacrifice and learn to deal with the sound. For several months I was working from midnight till 3 or 4 am to get some of my work done. So I started to think about going back to headphones. I’ve previously owned a set of a well known, expensive brand that was good - well, great sound, but they were big and got to be far too hot on my head, especially over time. So I ended up getting rid of those. I still wear a set of those that sit on the outside of my ears for sound - which is outstanding - but they don’t always cover enough noise as they were designed to allow the athletes who wear them to actually hear sound around them. So....<br /><br />I was thinking what I might do again. I had the chance to get these Ankbit Hybrid Active Noise Cancelling Headphones, but went in knowing they too might be too hot on my head after awhile. I figured I’d at least get some work done in a few hours each day.... but would they be enough?<br /><br />I should also mention, I have a lifelong issue with my ears that causes me to feel the pressure (think airplanes and storms) in such a way it can bother my head. The other reason I got rid of those expensive well know headphones was that they sat so securely on my head, the pressure was too much for my head. I again, could only wear them for so long before I had to take them off.<br /><br />So, these Ankbit Hybrid Active Noise Cancelling Headphones?<br />So far I really like them - a lot!<br />I’ve been wearing them every day for at least a few hours and getting work done. It has taken a bit of time to adjust, but what I am experiencing has been helpful and I am glad to have them.<br /><br />The box they come in includes the headset, a bag, and needed cords.<br /><br />The cords are easy to use, but I would say, it would be nice if the cord for charging were longer. I mean, this thing is SHORT! Where I could normally set an item off to the side with the cord reaching, I now have to set these headsets directly in front of the plug, meaning plugging in other things is difficult. So that would be one improved this set could use.<br /><br />The bag is great. It is black, nice material, and holds the headset well. Glad to have it.<br /><br />The Ankbit Hybrid Active Noise Cancelling Headphones themselves are surprisingly great. I don’t know why it surprises me, other than I had that expensive pair in the past - which was outstanding - and I like these as much - in some ways, more (think ear discomfort and overheating).<br /><br />1. The set is comfortable with the ear covers nice and soft on my ears. They are enough to sit well, hold in the sound (my wife has not complained about any sound bleed), and work as far as noise canceling. ** I'll come back to this in a minute. But I find the Ankbit Hybrid Active Noise Cancelling Headphones to be very comfortable. If I had one “complaint” it’s that they are slightly large. I have a large head on which I wear large hats. However, even I find the top of this to be a bit larger than my head - which tells me someone with a smaller head than mine might have an issue with the size of these. They do fit, and the ears sit directly on my ears, but I can tell it’s just on my ears. It is comfortable, but something I take note of.<br /><br />2. There is no (noticeable) pressure build up. Where my previous set caused such pressure that I’d have to take them off at least twice an hour, I’ve never had to take these off and have worn them up to 3 hours at a time - and could go longer.<br /><br />3. ** The noise reduction works. We tested this the first day - including matching to another work style head set I got to also try and block the noise - the kind used on construction sites and the like - and this Ankbit Hybrid Active Noise Cancelling Headphones worked as well or perhaps better than that set. While that set has no music or sound to it and this does, both blocked my wife’s talking and yelling within 2 - 3 feet of me to the point that I could barely hear her. This Ankbit Hybrid Active Noise Cancelling Headphones offers the music as a way to add to the options - and I use an app to help if need be, with sounds such as white noise and thunderstorms. But in general, I prefer to be able to have no noise at all at times. With both the app sounds and no sound at all, I am able to block out MOST noise. I do add the app when my wife is working in the kitchen, which is behind my back where I’m working now she’s home. And the app takes care of the rest of the sound. But without it, I have great sound reduction and elimination.<br /><br />You can also turn this feature off and have “transparency” which allows you to hear background noise, incase you need to listen for the kids or a phone. It still. blocks the sound, gives you good internal sound with music, but you can hear outside sound better. It is like my other, outside the ear set when in this mode, so I do not use it - I have those for that type of sound. But it is available.<br /><br />4. The sound itself is excellent. I have listened to music and movies playing on these and both are outstanding. I truly love the sound and find it is full, rich, and well done. It’s a pleasant experience.<br /><br />5. The buttons for on/off, volume up/down, and transparency are at the side of the ear phone on the right side and 1. EASY to the point of frustration that I keep hitting them - usually turning it off - when trying to remove the headset,  and needing to learn how to not hit them and 2. easy to use overall. The four buttons are easy to adjust - I’m still getting use to which is which and not second guessing. The on/off is easy, but I’m really impressed with the volume up/down, which is in nice levels of degrees - not too much either way - and gives a great sound.<br /><br />I also discovered - the hard way - when you close the computer it’ll go off, but open and it’s back up and running. There are so many little things like that. I don’t know, maybe they are far more common than I know - I have not been a headset user for some time - but these are details that impress.<br /><br />Overall I really like this Ankbit Hybrid Active Noise Cancelling Headphones for my work and the quiet it provides, but for the sound I get when I’m listening to sounds to help me work, or even better, the music and movies that help keep me going throughout the day. I’m impressed and if this set lasts for a few years... it’ll be an outstanding find!",
 'Excellent nic Easy to install and works great.',
 "I like it DH recommended it based on his previous purchases of LG products.  I'm satisfied, and the Windows screen snap feature didn't require the installation of any special software to get the double screen effect.",
 'Excellent quality at a competitive price Links at a full gigabit and is capable of providing a full gig in each direction with my fiber connection.',
 'Beautiful Beautiful art for my dining room. great quality and great price',
 "after using the mini-cd that came with it to install the drivers it's worked like a charm not the plug n play... turn the machine off install and vola! after using the mini-cd that came with it to install the drivers it's worked like a charm. Easy upgrade options instead of replacing tons of parts just to get the 1000Mbps speed vs. 100.",
 'Four Stars good stuff',
 'Good value I like amount of faces I can use from the app.  I also like that I can set it to vibrate when I get calls.  I do not use it for messaging.  Good value.',
 "Great for movie night! I got this screen to use with our projector for better viewing quality.  We originally planned to use a large blank wall in our great room or the vinyl privacy fence in the backyard to watch movies via the projector, but quickly realized that a projection screen was a must (lol).  The ultra smooth surface of this generously sized projector screen gives a crisp clear picture quality.  And the stand gives you the flexibility of using it indoors or outdoors.  It's quick and easy to set-up and take down.  Doesn't take up alot of storage space which is nice.  Overall, a quality made projection screen.  We look forward to many family movie nights to come!",
 'does NOT work with apple products Does NOT work for iPhone products. Only actual product bought from Apple will work with their products.<br />Don’t believe the lies, just fork over the money for the real deal and save yourself time and money AND frustration by not having to return these boogers after you don’t take this advice!😜',
 'Five Stars High quality!!',
 "Great little widescreen monitor I was looking for a smaller widescreen monitor to use as a 3rd monitor above my two main ones. I also have a shelf on the wall above my monitors so my space is limited. Based on the dimensions of this it would fit perfectly in the space and it did! I mostly use it for browsing and background TV while I work and its great for that.<br /><br />I'm not sure I would be happy with this as a main monitor because of the odd resolution, but as a secondary or tertiary monitor I think its fantastic! It was exactly what I wanted and has performed beautifully.",
 'Easily Installed and Worked My internet connection was lost on my XP video machine.  I tried updating the driver with no luck.  Purchased this card and a computer store installed it for me.  They also fixed my motherboard access so now I have two outlets working.',
 "It's cheap. It's simple. It works. I took on a project where I recycled one of my PCs and turned it into a firewall/router for my home network. The only thing I was lacking for the project was a second gigabit Ethernet adapter. I've actually used quite a bit of TP-Link's networking gear in recent years, so I figured that I might as well give this inexpensive PCIE gigabit Ethernet card a shot.<br /><br />Long story short, the card works like a champ. It was easily detected by the firewall software that I used for the install, which is based on the BSD operating system. Since it easily autodetects in BSD I would assume that it works equally well with Linux. I did not bother testing it on a Windows installation, so you should check the manufacturer's specs to make sure that it works with whatever version of that operating system you happen to be using before buying.<br /><br />Autodetection of the card worked without a hitch and the card is now operating on my gigabit LAN at full duplex with no problems whatsoever. It's simple. It's cheap. It works. That is about the best I can say for any product.",
 'For kids Bought these for a flight to keep the grand kids entertained.  Worked out well.',
 "Plug-n-play with multiple OS's Purchased for a friend who needed a simple drop-in card for his Win7 x64 machine. He was able to drop it right in, Windows automagically installed the drivers and he was back online in a matter of minutes. Based on searching for other cards, this one seemed to offer the best chipset and driver compatibility for the price.",
 'Great product but no power output It does the basics and has all the basics you need to work from home. I don’t like controlling the buttons from under the screen. I don’t like the fact It doesn’t work well with my surface pro from work. I can’t use the wide screen on the surface pro. The speakers are good but not like the MacBook M1. My MacBook works great in wide screen and it was easy to step up. I had to get a docking station because the monitor had no power output to charge my MacBook. It will charge my iPhone. I have connect external adaports. I wish this came with more ports and a power output but I guess we get what we pay for. The size fits perfectly on my Micke desk from IKEA in my closet at home.',
 "My main monitor I need two screens to do most of my work.  I was using my laptop and a much larger screen.  But I was getting tired of looking back and forth and seeing two different resolutions/sizes of the applications I use (I know, first world problem).  This ultrawide was a good price and the other monitor I have and really like is an LG, so I took a chance.  It's just what I needed.  Would I have liked a curved monitor?  Absolutely, but I also didn't want to pay $600 for it.  This does the job!  I have two browser sessions open on it at all times. The picture is very clear and bright.  The speakers also work well!  I don't do any gaming or anything with this, it's for work.<br /><br />I'm using the stand it came with.  It didn't take too long to put together and I can rotate the screen to the left and right.  It does not slant up or down at an angle, but you can easily choose a different height from within the stand.  I've never needed to rotate it vertically, but that's easy to do as well.  The monitor itself is very light, the stand is plenty secure.",
 'Good network card I bought this card because it was cheap but it also works really well. I got full gigabit speeds from this with no issues.',
 'Five Stars Excellent! Love it!',
 "Too Tall for my needs I didn't realize this at first but just having a PCIe x1 slot doesn't mean it'll allow the case to close. This card sticks out about 3/4&#34; too high to close my case (note: this is a small form factor pfSense install)<br /><br />Not $$ enough to bother returning so I found a different one on Amazon that's only 1.5&#34; high and will hopefully fit<br /><br />Now what to do w this one?",
 'Seems to be working fine, I have more than double some network speeds ... Seems to be working fine, I have more than double some network speeds and now my bottleneck is the hard drives.',
 "Comfortable, noise cancelling works These headphones were purchased for our 12 year old grandson for Christmas. He put them on immediately after opening them replacing the other headphones he already had. We stayed a week and he wore them every chance he could. He said he loved them, they were very soft and comfortable and the noise cancelling worked way better than his other headphones. We would recommend and will probably purchase again as soon as the next grandchild's birthday comes along.",
 "Nice new look for my fenix 5 This order arrived promptly, fit perfectly, and looks great.  It is genuine leather and a little stiff, as expected, at first--but quickly relaxed.  I like the subtle red stripe.  I haven't had it long enough to confidently comment on durability, but it seems rugged enough to last.  Strongly recommend!",
 'Good NIC for good price. Good inexpensive NIC to replace your dead motherboard or for a second network',
 "Fast, but with some issues. With 4 sticks of RAM, I can only get the memory to run at 4000Mhz.<br />With 2 sticks, it is only stable at 5400.<br />The RAM is 5600mhz, and is on the compatible list from MSI.<br /><br />So, no matter what make sure you run RAM tests and prime95.<br />POST also takes ages, unless you turn on memory context restoring... but that can cause memory glitches.<br /><br />I don't know how much of this is the Ryzen 9 7950X and how much of it is the motherboard...<br />But this seems to be a really common issue at the moment.<br /><br />Hopefully this can all be improved with BIOS/Microcode updates...<br />But not hearing anything from MSI or AMD about these issues is very worrying.<br />That having been said, overall the board is well made.",
 "Great Network Card This is my third TP-Link device I get and I'm really happy with the brand.<br /><br />The network card comes with full status lights, so you can identify the network card (they blink in a pattern) so you can identify this card to what windows adapter is attached in case you have several cards of the same brand, also a dedicated light to tell you if the connection is at 10 or 100 or 1000 mbps.<br /><br />This is attached to the main board using a PCI-E 1x slot, so is great for me because my board have a few of them but this is the first device I get to use it.<br /><br />The Wake On Lan feature works great, just need a few configurations to be made over windows to have this working.<br /><br />This network card is placed on a CPU running windows 7 x64, the driver comes in the companion CD an works really great.<br /><br />A really good option if you are looking for a Network card.",
 'Good quality, excellent performance and decent adapter options allow for fairly fine grained control Great performance for the price. Easy to install, perfect for use in towers to mini-ITX PCs. Good adapter options especially at this price point, gives fairly fine grained control over network packets traversing this NIC. Would definitely buy again.',
 'Perfect for RV Travels My husband loves this GPS for RV hauling.',

In [37]:
embeddings_reviews = get_embeddings_batch(text_to_embed_reviews, batch_size=500)

Processed 500 of 3943
Processed 1000 of 3943
Processed 1500 of 3943
Processed 2000 of 3943
Processed 2500 of 3943
Processed 3000 of 3943
Processed 3500 of 3943
Processed 4000 of 3943

In [38]:
len(embeddings_reviews)

3943

In [39]:
pointstructs = []
i = 1
for embedding, data in zip(embeddings_reviews, data_to_embed_reviews):
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload={
                "text": data["preprocessed_data"],
                "parent_asin": data["parent_asin"],
            }
        )
    )
    i += 1

In [40]:
batch_size_qdrant = 100
counter = 1
for i in range(0, len(pointstructs), batch_size_qdrant):
    batch = pointstructs[i:i + batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="Amazon-items-collection-01-reviews",
        wait=True,
        points=batch
    )
    print(f"Processed {counter * batch_size_qdrant} of {len(pointstructs)}")
    counter += 1

Processed 100 of 3943
Processed 200 of 3943
Processed 300 of 3943
Processed 400 of 3943
Processed 500 of 3943
Processed 600 of 3943
Processed 700 of 3943
Processed 800 of 3943
Processed 900 of 3943
Processed 1000 of 3943
Processed 1100 of 3943
Processed 1200 of 3943
Processed 1300 of 3943
Processed 1400 of 3943
Processed 1500 of 3943
Processed 1600 of 3943
Processed 1700 of 3943
Processed 1800 of 3943
Processed 1900 of 3943
Processed 2000 of 3943
Processed 2100 of 3943
Processed 2200 of 3943
Processed 2300 of 3943
Processed 2400 of 3943
Processed 2500 of 3943
Processed 2600 of 3943
Processed 2700 of 3943
Processed 2800 of 3943
Processed 2900 of 3943
Processed 3000 of 3943
Processed 3100 of 3943
Processed 3200 of 3943
Processed 3300 of 3943
Processed 3400 of 3943
Processed 3500 of 3943
Processed 3600 of 3943
Processed 3700 of 3943
Processed 3800 of 3943
Processed 3900 of 3943
Processed 4000 of 3943

### A function to run search against reviews on a prefiltered set of product IDs

In [41]:
def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-reviews",
        prefetch=[
            Prefetch(
                query=query_embedding,
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    return results

In [45]:
reviews = retrieve_prefiltered_reviews_data("bad quality", ["B0BWVD7KZG"])

In [46]:
reviews.points

[ScoredPoint(id=3229, version=34, score=0.5, payload={'text': 'Band has broken twice Poor Band quality', 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=189, version=3, score=0.33333334, payload={'text': "Junky piece What a cheap piece. I wouldn't waste your money.", 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=664, version=8, score=0.25, payload={'text': 'Cheap quality I’ve only had this watch for one month and it broke already! The hook came off completely. Very poorly made.', 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3369, version=35, score=0.2, payload={'text': 'Poor quality watches I bought two watches for my kids one month ago, the battery is shortly use, only 1-2days needs to charge, finally its were not working just one month it totally broke without any attacking, but it already pass the deadline.', 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3402, version=36, score=0.16666667, payload={'text': "It's junk very unhappy Junk", 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None)]

In [47]:
reviews = retrieve_prefiltered_reviews_data("bad quality", ["B0BWVD7KZG", "B0BGJ2TDXV"])

In [48]:
reviews.points

[ScoredPoint(id=3229, version=34, score=0.5, payload={'text': 'Band has broken twice Poor Band quality', 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=189, version=3, score=0.33333334, payload={'text': "Junky piece What a cheap piece. I wouldn't waste your money.", 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=664, version=8, score=0.25, payload={'text': 'Cheap quality I’ve only had this watch for one month and it broke already! The hook came off completely. Very poorly made.', 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3369, version=35, score=0.2, payload={'text': 'Poor quality watches I bought two watches for my kids one month ago, the battery is shortly use, only 1-2days needs to charge, finally its were not working just one month it totally broke without any attacking, but it already pass the deadline.', 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3402, version=36, score=0.16666667, payload={'text': "It's junk very unhappy Junk", 'parent_asin': 'B0BWVD7KZG'}, vector=None, shard_key=None, order_value=None)]

In [52]:
reviews = retrieve_prefiltered_reviews_data("bad quality", ["B0BWVD7KZG", "B0BGJ2TDXV"], k=20)

In [53]:
for point in reviews.points:
    print(point.payload["parent_asin"])
    print(point.payload["text"])
    print("-"*100)

B0BWVD7KZG
Band has broken twice Poor Band quality
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Junky piece What a cheap piece. I wouldn't waste your money.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Cheap quality I’ve only had this watch for one month and it broke already! The hook came off completely. Very poorly made.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Poor quality watches I bought two watches for my kids one month ago, the battery is shortly use, only 1-2days needs to charge, finally its were not working just one month it totally broke without any attacking, but it already pass the deadline.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
It's junk very unhappy Junk
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Poor unreadable instructions. Everything was not professional.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Quality for the price This is a great quality watch. The band is strong and the screen is a perfect size. The features look awesome. I disliked the fact that the fitbit couldn't bind with the scan code on the watch face. This causes the clock and all the features not to work.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
DISAPPOINTING I greatly dislike how this watch face blacks out after a few seconds. I wish I didn't have to push a button to read the time. I also don't think it is accurate as far as other things are such as supposedly reading blood pressure or heart beat. It's a bogus watch, I should have surmised this by the cheap price though. It's my fault I bought it.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
One of the most poorly made products I have purchased from Amazon! This is the 3rd time I have had to return this item.<br />This is the 3rd watch that I was sent (exact same model) and the strap broke on this watch after LESS than a month of light use.<br /><br />Avoid this product at all costs. Very poorly made, which is why the price is so low.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
its cheap, nothing brutal to expect here Well, bought them just cause i wanted bigger clock screen. For its price, its okey. Nothing special about the app of the watches. Low fuctionality. Sleep tracking is bad. Battery life kinda okey.<br /><br />It worth its money, but its cheap, so dont expect magic here
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Quality Seems to have a lot of features for the price.  Has a quality look and feel.  Everything is defaulted to metrics, so takes a bit to change .  Haven't tested several things yet, but so far so good.<br />Update:  Charges quick and lasts a long time, call and text notification is good, sleep tracking is good, step counter seems accurate enough<br />con:  heart rate bpm is off, lags, and rarely seems to get close.  For example, when exercising and I check the heart rate with a clock at 120 bpm, it may show only 90.  Still, for the price, it seems fair enough.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Amezing product Nice product,good quality i am happy with this
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
review very good, just what i wanted<br /><br />and great price!
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Had this 3 weeks...see the pic. Peeling Easy to use, comfortable, but it records crocheting as steps and blood pressure systolic reading is 30 to 40 points too high.  Not bad for a cheap watch, but if you want to measure blood pressure, get something else.<br /><br />Update had this 3 weeks.  Coating is peeling off.  CRAP...KEEP LOOKING.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Watch band Don't get the pink . Everything fades onto it and it looks tacky. I just figure that's what I get for going with a cheaper model I don't wear it any more. It has blue and black transfered to it. I am disappointed about it. I will simply go back to the name brand.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Cheap wrist band All functions of smart watch were great. Unfortunately the wrist band started coming apart in a very short time. I wish more care would be taken in designing the bands.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Great quality! I am very happy with this watch! I have tried others that were not as detailed and script is bright and clean.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Inaccurate numbers This product does not give accurate numbers which I ordered due to heart AFib. Don't have a printer or a UPS dropoff and customer service, Prshanea, told me to fine a neighbor that would print it!! Very disappointed in Amazon and will keep the watch.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Waste of money Not even a month old and it simply stopped working.<br />Impossible to find any kind of literature on the web, is there even a manufacturer site for support?<br /><br />Don't waste your money.
----------------------------------------------------------------------------------------------------
B0BWVD7KZG
Only buy if you want a watch with a customizable screen This watch does not work at all. i bought it mainly for the blood pressure and step counter. the BP gets the same reading every time... even if someone with low blood pressure uses it 140/79. the step counter is counting now as i sit at my desk at work writing this review. it counted 200 in an hour of sitting and 100 over 7 hours of sleep last night. It appeared that the sleep monitor was the only thing that worked, as it did record exactly when i went to bead and when i woke up in the middle of the night, without me doing anything....only i took a 1.5 hour nap just now and it didnt record it. cant manually change data..
----------------------------------------------------------------------------------------------------